database:
  host: "64.227.37.97"
  username: njclabs
  password: "![Hx0Zn8cS4alPi5z90V0ytQ==]"
  port: "3306"
  schema: nrs

http:
  port: "8082"

serviceNow:
  port: "8087"
  host: "0.0.0.0"
  protocol: "HTTP"
  clientId: "452e961bff2c4e899f09a3afb5ffa099"
  clientSecret: "5447C65c460F4a9583f632B26C3c6c7a"