#%RAML 1.0
title: National Railway Train Services API
version: 1.0.development
baseUri: http://localohost:8082/api/

uses:
  custlib: /exchange_modules/ce59e7c2-b990-4fe5-98a4-b5dba8efff20/customer-library/1.0.0/customer-library.raml

traits:
  client-id-required: !include /exchange_modules/ce59e7c2-b990-4fe5-98a4-b5dba8efff20/customer-trait/1.0.0/customer-trait.raml

/customers:
  is:
    - client-id-required
  get:
    description: Retrieve the customer details from the system
    responses:
      200:
        body:
          application/json:
            type: custlib.CustomerType
            examples:
              output: !include /Examples/customerExample.raml
      400:
        body:
          application/json:
            example:
              description: Error message
              message: Error in retrieving data, Please check through!
  post:
    description: Create a customer
    body:
      application/json:
        description: Customer created with respective details
        type: custlib.CustomerType
        examples:
          input: !include /Examples/customerNoIDExample.raml
    responses:
      201:
        body:
          application/json:
            example:
              description: Success Message
              message: Customer Registered Successfully!
      400:
        body:
          application/json:
            example:
              description: Error Message
              message: Error in inserting data, Please check through!
  /{id}:
    is:
      - client-id-required
    get:
      description: Retrieve customer details by ID
      responses:
        200:
          body:
            application/json:
              type: custlib.CustomerIdType
              examples:
                output: !include /Examples/customerByIdExample.raml
        400:
          body:
            application/json:
              example:
                description: Error Message
                message: Error in retrieving customer details by ID
    patch:
      description: Update Customer details by ID
      body:
        application/json:
          type: custlib.CustomerIdType
          examples:
            input: !include /Examples/customerByIdExample.raml
    
    /subscriptions:
      is:
        - client-id-required
      get:
        description: Retrieve all subscriptions of customers
        responses:
          200:
            body:
             application/json:
              type: custlib.SubscriptionType
              examples:
                output: !include /Examples/subscriptionExample.raml
          400:
           body:
            application/json:
              example:
                description: Error Message
                message: Error in retrieving customer subscriptions 
      post:
        description: Create subscription for each customer
        body:
          application/json:
            type: custlib.SubscriptionType
            examples:
              input: !include /Examples/subscriptionNoIDExample.raml
        responses:
          200:
            body:
              application/json:
                example:
                 description: Success message
                 message: Subscription added successfully 
          400:
            body:
              application/json:
                example:
                  description: Error message
                  message: Error in creating subscription data, Please check through!
      /{subscriptionId}:
        is:
          - client-id-required
        get:
          description: Retrieving each subscription data
          responses:
            200:
              body:
                application/json:
                  type: custlib.SubscriptionIdType
                  examples:
                    output: !include /Examples/subscriptionByIdExample.raml
            400:
              body:
                application/json:
                  example:
                    description: Error Message
                    message: Error in retrieving specific subscription data
        patch:
          description: Update Subscription details by ID
          body:
            application/json:
              type: custlib.SubscriptionIdType
              examples:
                input: !include /Examples/subscriptionByIdExample.raml

        /alerts:
          is:
            - client-id-required
          get:
            description: Retrieve all alert notifications data under particular subscription
            responses:
              200:
                body:
                  application/json:
                    type: custlib.AlertType
                    examples:
                      output: !include /Examples/alertsExample.raml
              400:
                body:
                  application/json:
                    example:
                      description: Error Message
                      message: Error in retrieving alert data for each subscription 
          post:
            description: Create new alert
            body:
              application/json:
                type: custlib.AlertType
                examples:
                  input: !include /Examples/alertNoIdExample.raml
            responses:
              201:
               body:
                 application/json:
                   example:
                     description: Success message
                     message: Alert tracking data added successfully 
              400:
                body:
                  application/json:
                    example:
                      description: Error message
                      message: Error in creating alert notiifications data, Please check through!
          /{alertId}:
            is:
              - client-id-required
            get:
              description: Retrieve specific alert notification data
              responses:
                200:
                  body:
                    application/json:
                      type: custlib.AlertIdType
                      examples:
                        output: !include /Examples/alertByIdExample.raml
                400:
                  body:
                    application/json:
                      example:
                        description: Error Message
                        message: Error in retrieving specific alert data
            patch:
              description: Update Alert details by ID
              body:
                application/json:
                  type: custlib.AlertIdType
                  examples:
                    input: !include /Examples/alertByIdExample.raml
  /sfdc:
    is: 
      - client-id-required
    get:
      description: Subscribed customer details integrated to Salesforce
      responses:
        200:
          body:
            application/json:
              example:
                description: Success
                message: "Successfully Integrated" 
        400:
          body:
            application/json:
              example:
                description: Error
                message: "Error in integrating customers data to Salesforce"